version: '3.9'

services:
  keycloak:
    container_name: "keycloak"
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: cns
      DB_SCHEMA: public
      DB_PASSWORD: cns
      KEYCLOAK_USER: cns
      KEYCLOAK_PASSWORD: cns
    ports:
      - 5050:8080
    networks:
      - my-proxy-net

networks:
    my-proxy-net:
        external:
            name: custom_network  