version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:12-buster
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: cns
      POSTGRES_PASSWORD: cns
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - my-proxy-net

volumes:
  postgres:
    external: true

networks:
  my-proxy-net:
    external:
      name: custom_network  